const config = require('../../../gulp-configuration.js'),
    del = require('del'),
    log = require('fancy-log'),
    upath = require('upath'),
    rls = require('remove-leading-slash'),
    filecopy = require('filecopy'),
    fs = require('fs'),
    prependFile = require('prepend-file'),
    os = require('os'),
    confirm = require('confirm-simple');


module.exports = {
    clean: function (echo, callback) {
        var success = true;
        confirm('Generated assets will be erased. Continue?', function (y) {
            if (y) {
                if (echo) {
                    log.info('Starting cleaning...');
                }
                var paths_to_erase = [
                    rls(config.generateFavicon.output)
                ];
                if (config.generateGitignore.enable) {
                    paths_to_erase.push(rls('./.gitignore'));
                }
                if (config.generateJs.enable) {
                    paths_to_erase.push(
                        rls(upath.join(rls(config.generateJs.output_path), config.generateJs.output_name + '.js')),
                        rls(upath.join(rls(config.generateJs.output_path), config.generateJs.output_name + '.js.map'))
                    );
                }
                if (config.generateCss.enable) {
                    paths_to_erase.push(
                        rls(upath.join(rls(config.generateCss.output_path), '*.css')),
                        rls(upath.join(rls(config.generateCss.output_path), '*.css.map'))
                    );
                }
                if (config.generateHtml.enable) {
                    paths_to_erase.push(rls(upath.join(rls(config.generateHtml.output), '*.html')));
                }
                del(paths_to_erase).then(function () {
                    if (config.generateGitignore.enable) {
                        filecopy(rls(upath.join(rls('./gulp-includes/'), rls('.gitignore'))),
                            './.gitignore', {
                                mkdirp: true
                            }
                        ).then(function () {
                            fs.appendFileSync('./.gitignore', os.EOL + '### /!\\ Do not edit this file. See : gulp-includes/.gitignore /!\\ ###');
                            prependFile('./.gitignore', '### /!\\ Do not edit this file. See : gulp-includes/.gitignore /!\\ ###' + os.EOL);
                            if (callback) {
                                callback(success);
                            }
                        }).catch(function (e) {
                            log.error(e);
                            success = false;
                            if (callback) {
                                callback(success);
                            }
                        });
                    }
                    else {
                        success = false;
                        if (callback) {
                            callback(success);
                        }
                    }
                });
            } else {
                if (callback) {
                    callback(success);
                }
            }
        });
    }
};